# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(527, 432)
        MainWindow.setStyleSheet("background-color: rgb(1, 9, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(140, 10, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.title.setFont(font)
        self.title.setStyleSheet("color: rgb(9, 162, 20);")
        self.title.setObjectName("title")
        self.cmd = QtWidgets.QLineEdit(self.centralwidget)
        self.cmd.setGeometry(QtCore.QRect(60, 250, 151, 25))
        self.cmd.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.cmd.setText("")
        self.cmd.setObjectName("cmd")
        self.cmd_label = QtWidgets.QLabel(self.centralwidget)
        self.cmd_label.setGeometry(QtCore.QRect(80, 220, 111, 20))
        self.cmd_label.setStyleSheet("color: rgb(238, 238, 236);")
        self.cmd_label.setObjectName("cmd_label")
        self.connect = QtWidgets.QPushButton(self.centralwidget)
        self.connect.setGeometry(QtCore.QRect(60, 80, 111, 25))
        self.connect.setStyleSheet("color: rgb(238, 238, 236);")
        self.connect.setObjectName("connect")
        self.disconnect = QtWidgets.QPushButton(self.centralwidget)
        self.disconnect.setGeometry(QtCore.QRect(300, 80, 101, 25))
        self.disconnect.setStyleSheet("color: rgb(238, 238, 236);")
        self.disconnect.setObjectName("disconnect")
        self.send = QtWidgets.QPushButton(self.centralwidget)
        self.send.setGeometry(QtCore.QRect(100, 290, 61, 25))
        self.send.setStyleSheet("color: rgb(238, 238, 236);")
        self.send.setObjectName("send")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(330, 180, 67, 17))
        self.label.setStyleSheet("color: rgb(238, 238, 236);")
        self.label.setObjectName("label")
        self.status_label = QtWidgets.QLabel(self.centralwidget)
        self.status_label.setGeometry(QtCore.QRect(80, 140, 67, 17))
        self.status_label.setStyleSheet("color: rgb(9, 162, 20);")
        self.status_label.setObjectName("status_label")
        self.status = QtWidgets.QLabel(self.centralwidget)
        self.status.setGeometry(QtCore.QRect(170, 140, 301, 17))
        self.status.setStyleSheet("color: rgb(9, 162, 20);")
        self.status.setObjectName("status")
        self.output = QtWidgets.QTextEdit(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(280, 210, 171, 181))
        self.output.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.output.setObjectName("output")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 527, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Reverse Shell"))
        self.title.setText(_translate("MainWindow", "Reverse Shell"))
        self.cmd_label.setText(_translate("MainWindow", "Enter command"))
        self.connect.setText(_translate("MainWindow", "Start Server"))
        self.disconnect.setText(_translate("MainWindow", "End Server"))
        self.send.setText(_translate("MainWindow", "Send"))
        self.label.setText(_translate("MainWindow", "Output"))
        self.status_label.setText(_translate("MainWindow", "Status"))
        self.status.setText(_translate("MainWindow", "Server Not Live"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
